### ISSUE TITLE
ng-class binding issue

### ISSUE THREAD

**Issue by stephenlautier** [kasperlewau/angular-bind-notifier#4]
Hi,

I'm trying to use this plugin since it seems pretty much what I need, in order to do further optimizations however I can't get it working.

I'm trying to use it for ng-class with the following syntax:
```
<a href="{{::node.slug}}" ng-class=":refresh:{'selected': node.isSelected}">{{::node.name}}</a>
```
Most probably its failing because of the colon in `'selected':` which is causing the parsing to crash

**Comment by kasperlewau** [comment]
Yep, that is most certainly it. 

Cross reference issue: #3

**Comment by kasperlewau** [comment]
Until I get a fix in there you could go with something aching to this: 

```js
$scope.someClassFunc = function (node) {
  return node.isSelected ? 'selected' : '';
};
```

```html
<div bind-notifier="{refresh: expr}">
  <a ng-class=":refresh:someClassFunc(node)">
</div>
```

--- 

Suffice to say that is not optimal, but it *should work™* in the meantime until I can get some time on my hands to fix the notifier/expression splitter working properly.

**Comment by stephenlautier** [comment]
Will give that a go for the time being, cheers!

**Comment by stephenlautier** [comment]
its kind of working by doing almost as you told me
so in the view i have this:
```
<a href="{{::node.slug}}" ng-class=":refresh:vm.isNodeSelectedClass(node)">{{::node.name}}</a>
```
in my controller i implemented the function
```
isNodeSelectedClass(node) {
	return node.isSelected ? "selected": "";
}
```
instead of the `bind-notifier` directive I'm using the manual way e.g. `this.$scope.$broadcast("$$rebind::refresh");`

it works technically, however with every rebind I believe the broadcasts registrations are being registered exponentially. 
When i put a break point on angular `$broadcast`and debug for `name === "$$rebind::refresh"`, I can see that the `target.$$listenerCount` amount is being increased dramatically with every click, and its killing my browser after 3-4x clicks

**Comment by kasperlewau** [comment]
Hmm. That sounds utterly funky, would you mind supplying a plunker/jsbin to highlight the problem?

**Comment by kasperlewau** [comment]
As an aside, the original issue as described here is now *partially fixed*, by https://github.com/kasperlewau/angular-bind-notifier/commit/f0a187f53bcfefff4781696b4da7c3a14cd51efa. 

The one gotcha there is to it is that you absolutely **must** supply a whitespace after the `:` where you wish for the expression to **not** split. 

That is to say: 
```html
  <a ng-class=":n1:n2:n3:{c1: c1Expr, c2: c2expr}"></a>
  <!-- notifiers: n1, n2, n3. expression: {c1: c1Expr, c2: c2Expr} -->

  <a ng-class=":n1:n2:n3:{c1:c1Expr, c2:c2Expr}"></a>
  <!-- notifiers: n1, n2, n3, {c1, 'c1Expr, c2', c2Expr}. expression: none. -->
```

The second example would crash, burn and die. horribly. I'm by no means great (or even, good) at regexes so if someone has a better solution I'm all for it. 

If someone can translate the following into a regex and supply some tests for it, that would take the cake; 

`split at colons, so long as said colon is not surrounded by angle brackets, or is immediately followed by an opening angle bracket`. That way we *should* catch all the notifiers, allow for object literals, as well as nested object literals. 

@tregusti - got some spare time on your hands? :smile:

**Comment by stephenlautier** [comment]
I got a repro of what I'm trying to do, and the issue with the $on being increased with every refresh

http://jsbin.com/quromeqihi/1/edit?html,css,js,output

This is how you should test it:
 - Go to link
 - Add a break point on angular.js on line 14766 ($broadcast)
 - Press Add from the UI
 - See the target.$$listenerCount
 - Keep doing the above e.g. Add and check count

They keep increase exponentially.

Also it doesn't seem to work if i just use `class` rather than `ng-class` you can check it at the demo too

**Comment by kasperlewau** [comment]
I'll take a look at it when I get back home, but unfortunately I won't be able to fully investigate/take care of the issue as I left my workhorse at work. 

Would you mind creating a separate issue for this case? I feel like this is derailing from a syntax related issue to a performance concern.

**Comment by kasperlewau** [comment]
Oh and thanks for the jsbin :)

**Comment by stephenlautier** [comment]
No problem, I will add a new issue for this, thanks!

**Comment by kasperlewau** [comment]
Closed by #8
